#! /bin/sh

sxhkd &
polybar -r top &
nm-applet &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           9
bspc config top_padding         12
bspc config right_padding       12
bspc config bottom_padding      12
bspc config left_padding        12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config normal_border_color  "#282a36"
bspc config active_border_color  "#44475a"
bspc config focused_border_color "#44475a"
