#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload
hsetroot -solid '#282a36'
hc pad 0 31

# remove all existing keybindings
hc keyunbind --all

# start the compositor, compton
pkill compton
compton &

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

udiskie --tray --use-udisks2 &

# keybindings
Mod=Mod4   # Use the super key as the main modifier
TERMINAL=alacritty

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn ${TERMINAL:-xterm} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Shift-space spawn rofi -show drun
hc keybind $Mod-backslash spawn $HOME/bin/rofi-pass
hc keybind $Mod-Alt-l spawn i3lock -e -t
hc keybind $Mod-Alt-Control-l spawn bash -c 'i3lock -e -t && sleep 5 && systemctl suspend'

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-j or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-k or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-l or / shift right / \
    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( work code browse gimp android {6..9} chat )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc set focus_follows_mouse 1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#6272a4'
hc set frame_border_normal_color '#282a36'
hc set frame_bg_normal_color '#282a36'
hc set frame_bg_active_color '#44475a'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_active_opacity 0
hc set frame_normal_opacity 0
hc set frame_transparent_width 0
hc set frame_gap 12

hc attr theme.active.color '#8be9fd'
hc attr theme.normal.color '#282a36'
hc attr theme.urgent.color '#ffb86c'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

#hc attr theme.minimal.border_width 3
#hc attr theme.minimal.inner_width 2
#hc attr theme.minimal.active.color '#8be9fd'
#hc attr theme.minimal.normal.color '#282a36'
#hc attr theme.minimal.urgent.color '#ffb86c'
#hc attr theme.minimal.active.inner_color '#3E4A00'
#hc attr theme.minimal.active.outer_color '#3E4A00'

hc set window_gap 24
hc set frame_padding 1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc load android '
(split horizontal:0.200000:1
(split horizontal:0.250000:1
(clients vertical:1)
(clients max:1))
(clients max:1))
'
# Main Android Studio window
hc rule class="jetbrains-studio" title~"Android Studio$" tag=android index=1
# AVD Manager dialog
hc rule class="jetbrains-studio" title="Android Virtual Device Manager" tag=android index=1 pseudotile=on
# Settings
hc rule class="jetbrains-studio" title="Default Settings" tag=android index=1 pseudotile=on
# Emulator main window
hc rule title~"^Android Emulator -" windowtype='_NET_WM_WINDOW_TYPE_NORMAL' tag=android pseudotile=on index=01
# Emulator extra windows
hc rule windowtype='_NET_WM_WINDOW_TYPE_UTILITY' title="Emulator" index=00 pseudotile=on

# GIMP
# load predefined layout
hc load gimp '
(split horizontal:0.850000:0
(split horizontal:0.200000:1
(clients vertical:0)
(clients grid:0))
(clients vertical:0))
'
# center all other gimp windows on gimp tag
hc rule class=Gimp tag=gimp index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' \
pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1

# work
hc rule class="Google-chrome" tag=work
hc rule title~"Google Hangouts is sharing" tag=work manage=off focus=off

# chat
hc rule class=Signal tag=chat
hc rule class=Slack tag=chat

# unlock, just to be sure
hc unlock

hc set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" $monitor &
#done

# make sure we've got polybar runnin
pkill polybar
polybar main &
